spring.application.name=inst360

spring.datasource.url=jdbc:postgresql://localhost:5432/inst360_spring
spring.datasource.username=postgres
spring.datasource.password=ifsp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
